export interface IRazorpayOptions {
  description: string;
  image?: string;
  currency: string;
  key: string;
  amount: string;
  name: string;
  order_id: string;
  prefill: IRazorpayPrefill;
  theme?: IRazorpayTheme;
}

export interface IRazorpayPrefill {
  email?: string;
  contact?: string | null;
  name?: string;
}

export interface IRazorpayTheme {
  color: string;
}

// Generated by https://quicktype.io

export interface IRazorpayError {
  code: number;
  description: string;
  details: IRazorpayPrefill;
}

// Generated by https://quicktype.io

export interface IRazorpaySuccess {
  razorpay_signature: string;
  razorpay_order_id: string;
  razorpay_payment_id: string;
  checkout_logo: string;
  custom_branding: boolean;
  org_logo: string;
  org_name: string;
}
